### PR TITLE
SFT-251 Create Fault List Component

### PR DESCRIPTION
**Pull request by Ahmed-I-Abdullah**

### CODE REVIEW

**Review by Hesham-E — APPROVED** [review]
Looks good to me!

**Comment by DatLam25** [comment]
Screenshot from 2021-09-09 20-07-24
I do not know if this happen on other computers but the text get cut off on the end and that could be a problem with longer faults.

**Comment by Hesham-E** [comment]
That is a strange issue Dat. This doesn't happen on my machine. Did you resize the window by chance?

**Comment by DatLam25** [comment]
I did not, but even when I increase the size it is still the same.

**Comment by Ahmed-I-Abdullah** [comment]
Good catch! I didn't test longer texts, when changing the fault content to a longer string it gets cut off too. I'll try to fix it

**Review by DatLam25 — APPROVED** [review]

**Review by disneyonbryce — APPROVED** [review]

**Pull request merged**
